// Generated by "dolly install". Ambient dolly behavior for opencode:
//   - task context injected into every LLM call and across compaction
//   - a step auto-logged per finished turn
//   - turns mirrored to ~/.local/share/opencode/dolly/ for `dolly reindex`
// Every dolly shell-out swallows its errors. Safe to delete; re-created on install.
import { execFileSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";

export const DollyPlugin = async ({ client, directory, worktree }) => {
  const cwd = worktree || directory || process.cwd();
  const REFRESH_MS = 30_000;
  let cache = { at: 0, text: "" };
  let turnStartMs = Date.now();
  // messages already mirrored, per session — session.idle refires
  const seen = new Map();

  const dollyContext = () => {
    if (cache.text && Date.now() - cache.at < REFRESH_MS) return cache.text;
    try {
      cache.at = Date.now();
      cache.text = execFileSync("dolly", ["hook", "session-start", "--raw"], {
        cwd,
        encoding: "utf8",
        timeout: 15000,
      });
    } catch {
      cache.text = "";
    }
    return cache.text;
  };

  const textOf = (part) =>
    part && part.type === "text" && typeof part.text === "string" ? part.text : "";

  // one line describing a tool call, for the work chain; "" to omit
  const describePart = (part) => {
    if (!part || part.type !== "tool") return "";
    const name = String(part.tool ?? "tool");
    const state = part.state ?? {};
    const input = state.input ?? {};
    const file = input.filePath ?? input.file_path ?? input.path ?? input.notebook_path;
    if (/write|edit|patch|multiedit/i.test(name)) {
      return typeof file === "string" ? path.basename(file) : name;
    }
    if (/bash/i.test(name) && typeof input.command === "string") {
      const line = input.command.split("\n").map((l) => l.trim()).find(Boolean);
      return line ? line.slice(0, 90) : name;
    }
    if (/grep/i.test(name)) return `${name} ${String(input.pattern ?? "").slice(0, 60)}`;
    return name;
  };

  /**
   * The turn that just ended = every message after the ones we saw at the last
   * idle. Mirrored as one JSONL line in transcript.ts's Segment shape, then
   * piped to `dolly hook stop --from-stdin` for the auto-log.
   */
  const finishTurn = async (sid) => {
    let msgs = [];
    try {
      const res = await client.session.messages({ path: { id: sid } });
      const data = res?.data;
      msgs = Array.isArray(data) ? data : (data?.messages ?? []);
    } catch {
      return; // SDK unavailable — skip mirroring, never break the session
    }
    if (!Array.isArray(msgs)) return;
    const startIdx = seen.get(sid) ?? 0;
    seen.set(sid, msgs.length);
    const slice = msgs.slice(startIdx);
    if (!slice.length) return;

    const infoOf = (m) => m?.info ?? m ?? {};
    const partsOf = (m) => (Array.isArray(m?.parts) ? m.parts : []);
    const userMsg = slice.find((m) => infoOf(m).role === "user");
    if (!userMsg) return;

    const seg = {
      index: startIdx + 1,
      uuid: String(infoOf(userMsg).id ?? `${sid}:${startIdx}`),
      at: new Date(Number(infoOf(userMsg).time?.created ?? Date.now())).toISOString(),
      endedAt: new Date().toISOString(),
      prompt: slice
        .filter((m) => infoOf(m).role === "user")
        .flatMap((m) => partsOf(m).map(textOf))
        .filter(Boolean)
        .join("\n")
        .trim(),
      files: [],
      commands: [],
      tools: {},
      assistantTexts: [],
      workChain: [],
      thinking: [],
      sidechains: 0,
    };
    for (const m of slice) {
      const role = infoOf(m).role;
      for (const part of partsOf(m)) {
        if (role === "assistant") {
          const t = textOf(part);
          if (t.trim()) seg.assistantTexts.push(t.trim());
        }
        if (part?.type !== "tool") continue;
        const name = String(part.tool ?? "tool");
        seg.tools[name] = (seg.tools[name] ?? 0) + 1;
        const action = describePart(part);
        if (action) seg.workChain.push(action);
        const input = part.state?.input ?? {};
        const file = input.filePath ?? input.file_path ?? input.path;
        if (/write|edit|patch|multiedit/i.test(name) && typeof file === "string") {
          const rel = path.isAbsolute(file) ? path.relative(cwd, file) : file;
          if (rel && !rel.startsWith("..") && rel !== ".dolly" && !rel.startsWith(".dolly/")) {
            if (!seg.files.includes(rel)) seg.files.push(rel);
          }
        }
        if (/bash/i.test(name) && typeof input.command === "string") {
          const cmd = input.command.slice(0, 160);
          if (cmd && !seg.commands.includes(cmd)) seg.commands.push(cmd);
        }
      }
    }
    seg.workChain = compress(seg.workChain);

    try {
      const dir = mirrorDir();
      fs.mkdirSync(dir, { recursive: true });
      fs.appendFileSync(path.join(dir, `${sid}.jsonl`), JSON.stringify({ ...seg, session: sid }) + "\n");
    } catch {
      // mirror is best-effort
    }

    try {
      execFileSync("dolly", ["hook", "stop", "--from-stdin"], {
        cwd,
        input: JSON.stringify({
          agent: "opencode",
          session: sid,
          turn: seg.index,
          turnStartMs,
          text: seg.assistantTexts.join("\n"),
          tools: Object.keys(seg.tools),
          files: seg.files,
        }),
        encoding: "utf8",
        timeout: 15000,
      });
    } catch {
      // never break the session on a logging failure
    }
  };

  function compress(chain, max = 60) {
    const out = [];
    let last = "";
    let run = 0;
    for (const item of chain) {
      if (item === last) { run++; continue; }
      if (last) out.push(run > 1 ? `${last} ×${run}` : last);
      last = item;
      run = 1;
    }
    if (last) out.push(run > 1 ? `${last} ×${run}` : last);
    return out.length <= max ? out : [...out.slice(0, max), `… +${out.length - max} more actions`];
  }

  function mirrorDir() {
    const base =
      process.env.DOLLY_OPENCODE_DIR ||
      path.join(os.homedir(), ".local/share/opencode/dolly");
    return path.join(base, cwd.replace(/[^a-zA-Z0-9]/g, "-"));
  }

  /**
   * Display-only commands carry frontmatter "direct: true" and are meant to
   * show their output verbatim (/dolly-board), not have a model narrate it.
   * Interception happens in command.execute.before: the first !`cmd` line of
   * the template runs as a session shell message — its output lands in the
   * transcript without an LLM round-trip — then we throw, which skips the
   * model call. If the shell route fails we stand down and let the normal
   * prompt flow handle it instead of showing the user nothing.
   */
  const DIRECT = new Map();

  function scanDirectCommands() {
    const cfgHome = process.env.XDG_CONFIG_HOME || path.join(os.homedir(), ".config");
    const dirs = [
      path.join(cwd, ".opencode", "commands"),
      path.join(cfgHome, "opencode", "commands"),
    ];
    for (const dir of dirs) {
      let files = [];
      try {
        files = fs.readdirSync(dir);
      } catch {
        continue;
      }
      for (const f of files) {
        if (!f.startsWith("dolly-") || !f.endsWith(".md")) continue;
        const name = f.slice(0, -3);
        if (DIRECT.has(name)) continue;
        let md = "";
        try {
          md = fs.readFileSync(path.join(dir, f), "utf8");
        } catch {
          continue;
        }
        if (!/^direct:[ ]*true[ ]*$/m.test(md)) continue;
        const start = md.indexOf("!`");
        if (start === -1) continue;
        const end = md.indexOf("`", start + 2);
        if (end === -1) continue;
        DIRECT.set(name, md.slice(start + 2, end).trim());
      }
    }
  }

  /** $ARGUMENTS / ${ARGUMENTS:-default} / $1..$9, resolved before the shell sees them */
  function substituteArgs(tpl, args) {
    const list = args.trim() ? args.split(/\s+/) : [];
    let out = tpl;
    const DEF = "$" + "{ARGUMENTS:-";
    let idx;
    while ((idx = out.indexOf(DEF)) !== -1) {
      const end = out.indexOf("}", idx);
      const fallback = end === -1 ? "" : out.slice(idx + DEF.length, end);
      out = out.slice(0, idx) + (list[0] ?? fallback) + out.slice(end + 1);
    }
    out = out.split("$ARGUMENTS").join(args);
    for (let i = 9; i >= 1; i--) out = out.split("$" + i).join(list[i - 1] ?? "");
    return out;
  }

  async function runDirectCommand(input) {
    scanDirectCommands();
    const tpl = DIRECT.get(input.command);
    if (!tpl) return false;
    const cmd = substituteArgs(tpl, String(input.arguments ?? ""));
    try {
      await client.session.shell({
        path: { id: input.sessionID },
        body: { command: cmd, agent: "build" },
      });
      return true;
    } catch {
      return false; // shell route unavailable — normal prompt flow takes over
    }
  }

  return {
    // a new user turn began: reset timing and let the next LLM call re-read context
    "chat.message": async () => {
      turnStartMs = Date.now();
      cache.at = 0;
    },
    "experimental.chat.system.transform": async (_input, output) => {
      const ctx = dollyContext();
      if (ctx && ctx.trim()) output.system.push(ctx);
    },
    "experimental.session.compacting": async (_input, output) => {
      cache.at = 0; // compaction means long time passed; force fresh context
      const ctx = dollyContext();
      if (ctx && ctx.trim()) output.context.push(ctx);
    },
    "command.execute.before": async (input) => {
      let handled = false;
      try {
        handled = await runDirectCommand(input);
      } catch {
        handled = false;
      }
      // a throw here cancels the LLM prompt — the command already showed its output
      if (handled) throw new Error("dolly: display-only command");
    },
    event: async ({ event }) => {
      try {
        if (event?.type !== "session.idle") return;
        const sid = event.properties?.sessionID ?? event.properties?.info?.id;
        if (!sid) return;
        await finishTurn(String(sid));
      } catch {
        // never surface anything into the session
      }
    },
  };
};
