import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { JsonFileError, exists, isDir, readJsonForUpdate, readTextOr, rmrf, writeJson, writeText } from './core/fsx.js';
import { setBlock } from './core/md.js';
import { VERSION } from './core/pkg.js';
import { AGENT_BLOCK, MCP_SERVER } from './templates/instructions.js';

/**
 * The user's config home, resolved per call rather than at module load: a
 * global install writes into it, and a caller (a test, a sandbox) that changes
 * HOME must not be silently ignored because this was captured on import.
 */
function home(): string {
  return os.homedir();
}

export const PKG_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

export interface Target {
  id: string;
  label: string;
  /** true when this agent looks installed / used here */
  detect(project: string): boolean;
  install(project: string, opts: InstallOpts): string[];
}

export interface InstallOpts {
  mcp: boolean;
  dryRun: boolean;
  global: boolean;
  /**
   * install session-start / turn-end automation where the agent has it: Claude
   * Code hooks, the opencode plugin, the pi extension, the zcode plugin.
   * Default on.
   */
  hooks?: boolean;
}

function writeBlock(file: string, block: string, dry: boolean): string {
  const src = readTextOr(file);
  let next: string;
  try {
    next = setBlock(src, 'instructions', block);
  } catch (err) {
    // a start marker with no end: skip this file, keep installing the rest
    return `skipped ${file} — ${(err as Error).message}`;
  }
  if (next !== src && !dry) writeText(file, next);
  return `${next === src ? 'up-to-date' : 'wrote'} ${file}`;
}

/** Write a whole file, reporting up-to-date when the content already matches. */
function writeFileIdempotent(file: string, content: string, dry: boolean): string {
  const src = readTextOr(file);
  if (src === content) return `up-to-date ${file}`;
  if (!dry) writeText(file, content);
  return `wrote ${file}`;
}

/**
 * Adapt a Claude slash-command to a pi/opencode prompt template. Both share the
 * frontmatter and $ARGUMENTS syntax. pi has no inline `!`cmd`` execution — its
 * own prompts put commands in fenced bash blocks and let the agent run them —
 * so each `!`cmd`` line becomes a ```bash block. opencode runs `!`cmd`` natively,
 * so its commands pass through this unchanged. Everything else passes through.
 */
function toPiPrompt(md: string): string {
  return md.replace(/^!`(.+)`\s*$/gm, (_m, cmd) => `\`\`\`bash\n${cmd}\n\`\`\``);
}

/**
 * zcode command conversion. zcode rejects inline `!`cmd`` execution, so inline
 * shell becomes a fenced bash block (same as pi). `${ARGUMENTS:-x}` is not
 * shipped any more — no harness expanded it — but collapse it defensively.
 */
function toZcodeCommand(md: string): string {
  return toPiPrompt(md).replace(/\$\{ARGUMENTS:-[^}]*\}/g, '$ARGUMENTS');
}

/**
 * Install the dolly slash-commands as prompt templates (dolly-<name>.md).
 * pi discovers these under prompts/, opencode under commands/. `exec` controls
 * inline-shell handling: pi cannot run `!`cmd``, so those lines are rewritten
 * into fenced bash blocks; opencode runs them natively and gets the file as-is.
 */
function installNamedPrompts(dir: string, dry: boolean, exec: boolean): string[] {
  return installCommandFiles(dir, dry, (md) => (exec ? md : toPiPrompt(md)));
}

/**
 * Write every shipped command as `dolly-<name>.md` in `dir`, converted, and
 * delete `dolly-*.md` files the package no longer ships. Only the `dolly-`
 * prefix is ours: the user's own commands in the same directory are left alone.
 */
function installCommandFiles(dir: string, dry: boolean, convert: (md: string) => string): string[] {
  const src = path.join(PKG_ROOT, 'commands');
  if (!isDir(src)) return [];
  const out: string[] = [];
  const shipped = new Set<string>();
  for (const file of fs.readdirSync(src).sort()) {
    if (!file.endsWith('.md')) continue;
    shipped.add(`dolly-${file}`);
    out.push(writeFileIdempotent(path.join(dir, `dolly-${file}`), convert(readTextOr(path.join(src, file))), dry));
  }
  const removed = pruneDir(dir, (rel) => !rel.includes(path.sep) && /^dolly-.*\.md$/.test(rel) && !shipped.has(rel), dry);
  for (const r of removed) out.push(`removed ${path.join(dir, r)} (no longer shipped)`);
  return out;
}

/**
 * pi auto-inject extension. On before_agent_start it shells the existing
 * `dolly hook session-start` (which reads .dolly, no transcript) and prepends
 * its output to the system prompt. Deliberately untyped so it carries no
 * dependency on a pi package name, and fully wrapped so a missing dolly binary
 * or store never blocks a pi session.
 */
const PI_EXTENSION = `// Generated by \`dolly install\`. Gives pi the ambient dolly behavior:
//   - before_agent_start: inject the task context at session start
//   - agent_end: auto-log a step for the prompt that just finished
// Both shell the dolly binary and swallow every error, so a missing binary or
// store never blocks a pi session. Safe to delete; re-created on \`dolly install\`.
import { execFileSync } from "node:child_process";

export default function (pi) {
  pi.on("before_agent_start", (event) => {
    try {
      const ctx = execFileSync("dolly", ["hook", "session-start", "--raw"], {
        cwd: process.cwd(),
        encoding: "utf8",
        timeout: 15000,
      });
      if (ctx && ctx.trim()) {
        return { systemPrompt: event.systemPrompt + "\\n\\n" + ctx };
      }
    } catch {
      // dolly absent, no store, or timed out \u2014 leave the prompt untouched.
    }
  });

  // One step per user prompt: agent_start/agent_end bracket it. turn_end
  // fires once per LLM round (every tool loop), and its turnIndex restarts at
  // 0 on each prompt — keyed on it, prompt 2's first round was dropped as a
  // duplicate of prompt 1's while one prompt logged a step per round.
  let agentStartMs = Date.now();
  pi.on("agent_start", () => {
    agentStartMs = Date.now();
  });

  pi.on("agent_end", (event, ctx) => {
    try {
      const messages = Array.isArray(event?.messages) ? event.messages : [];
      const assistant = messages.filter((m) => m && m.role === "assistant");
      const blocks = assistant.flatMap((m) => (Array.isArray(m.content) ? m.content : []));
      const textOf = (m) =>
        (Array.isArray(m.content) ? m.content : [])
          .filter((b) => b && b.type === "text" && typeof b.text === "string")
          .map((b) => b.text)
          .join("\\n")
          .trim();
      // the last thing the agent said is its own summary of the prompt
      const text = assistant.map(textOf).filter(Boolean).pop() || "";
      const tools = [];
      const files = [];
      for (const b of blocks) {
        if (!b || (b.type !== "toolCall" && b.type !== "tool_use")) continue;
        if (b.name && !tools.includes(b.name)) tools.push(b.name);
        const a = b.arguments || b.input || {};
        const f = a.path || a.file_path || a.filePath;
        if (typeof f === "string" && !files.includes(f)) files.push(f);
      }
      if (!text && tools.length === 0 && files.length === 0) return;

      const payload = JSON.stringify({
        session: (ctx && ctx.sessionManager && ctx.sessionManager.getSessionId)
          ? ctx.sessionManager.getSessionId()
          : "",
        // unique per prompt, identical if the same event is replayed
        turn: String(agentStartMs),
        turnStartMs: agentStartMs,
        text,
        tools,
        files,
      });
      execFileSync("dolly", ["hook", "stop", "--from-stdin"], {
        cwd: process.cwd(),
        input: payload,
        encoding: "utf8",
        timeout: 15000,
      });
    } catch {
      // never block the turn on a logging failure.
    }
  });
}
`;

/**
 * opencode plugin. Gives opencode the same ambient behavior the Claude Code
 * hooks give Claude Code:
 *   - experimental.chat.system.transform: injects task context into every LLM
 *     call (fires per call, so the context is never staler than the last turn)
 *   - experimental.session.compacting: re-injects it across compaction
 *   - session.idle: auto-logs a step for the finished turn (via `dolly hook
 *     stop --from-stdin`, the same pipe pi uses) and mirrors the turn to
 *     ~/.local/share/opencode/dolly/<escaped-cwd>/<session>.jsonl in the
 *     Segment shape transcript.ts parses — that mirror is what `dolly reindex`
 *     reads, because opencode keeps its real store in SQLite with no stable
 *     on-disk format.
 * Untyped so it carries no dependency on an @opencode-ai package, and fully
 * wrapped so a missing dolly binary or store never blocks a session. Safe to
 * delete; re-created on `dolly install`.
 */
const OPENCODE_PLUGIN = `// Generated by "dolly install". Ambient dolly behavior for opencode:
//   - task context injected into every LLM call and across compaction
//   - a step auto-logged per finished turn
//   - turns mirrored to ~/.local/share/opencode/dolly/ for \`dolly reindex\`
// Every dolly shell-out swallows its errors. Safe to delete; re-created on install.
import { execFileSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";

export const DollyPlugin = async ({ client, directory, worktree }) => {
  const cwd = worktree || directory || process.cwd();
  const REFRESH_MS = 30_000;
  let cache = { at: 0, text: "" };
  let turnStartMs = Date.now();
  // messages already mirrored, per session — session.idle refires
  const seen = new Map();

  const dollyContext = () => {
    if (cache.text && Date.now() - cache.at < REFRESH_MS) return cache.text;
    try {
      cache.at = Date.now();
      cache.text = execFileSync("dolly", ["hook", "session-start", "--raw"], {
        cwd,
        encoding: "utf8",
        timeout: 15000,
      });
    } catch {
      cache.text = "";
    }
    return cache.text;
  };

  const textOf = (part) =>
    part && part.type === "text" && typeof part.text === "string" ? part.text : "";

  // one line describing a tool call, for the work chain; "" to omit
  const describePart = (part) => {
    if (!part || part.type !== "tool") return "";
    const name = String(part.tool ?? "tool");
    const state = part.state ?? {};
    const input = state.input ?? {};
    const file = input.filePath ?? input.file_path ?? input.path ?? input.notebook_path;
    if (/write|edit|patch|multiedit/i.test(name)) {
      return typeof file === "string" ? path.basename(file) : name;
    }
    if (/bash/i.test(name) && typeof input.command === "string") {
      const line = input.command.split("\\n").map((l) => l.trim()).find(Boolean);
      return line ? line.slice(0, 90) : name;
    }
    if (/grep/i.test(name)) return \`\${name} \${String(input.pattern ?? "").slice(0, 60)}\`;
    return name;
  };

  /**
   * The turn that just ended = every message after the ones we saw at the last
   * idle. Mirrored as one JSONL line in transcript.ts's Segment shape, then
   * piped to \`dolly hook stop --from-stdin\` for the auto-log.
   */
  const finishTurn = async (sid) => {
    let msgs = [];
    try {
      const res = await client.session.messages({ path: { id: sid } });
      const data = res?.data;
      msgs = Array.isArray(data) ? data : (data?.messages ?? []);
    } catch {
      return; // SDK unavailable — skip mirroring, never break the session
    }
    if (!Array.isArray(msgs)) return;
    const infoOf = (m) => m?.info ?? m ?? {};
    const partsOf = (m) => (Array.isArray(m?.parts) ? m.parts : []);
    // \`seen\` lives in memory: after an opencode restart it is empty, and
    // starting from 0 mirrored the whole history as one turn. Start from the
    // newest user message instead — the turn that just ended.
    let startIdx = seen.get(sid);
    if (startIdx === undefined) {
      startIdx = 0;
      for (let i = msgs.length - 1; i >= 0; i--) {
        if (infoOf(msgs[i]).role === "user") {
          startIdx = i;
          break;
        }
      }
    }
    seen.set(sid, msgs.length);
    const slice = msgs.slice(startIdx);
    if (!slice.length) return;
    const userMsg = slice.find((m) => infoOf(m).role === "user");
    if (!userMsg) return;

    const seg = {
      index: startIdx + 1,
      uuid: String(infoOf(userMsg).id ?? \`\${sid}:\${startIdx}\`),
      at: new Date(Number(infoOf(userMsg).time?.created ?? Date.now())).toISOString(),
      endedAt: new Date().toISOString(),
      prompt: slice
        .filter((m) => infoOf(m).role === "user")
        .flatMap((m) => partsOf(m).map(textOf))
        .filter(Boolean)
        .join("\\n")
        .trim(),
      files: [],
      commands: [],
      tools: {},
      assistantTexts: [],
      workChain: [],
      thinking: [],
      sidechains: 0,
    };
    for (const m of slice) {
      const role = infoOf(m).role;
      for (const part of partsOf(m)) {
        if (role === "assistant") {
          const t = textOf(part);
          if (t.trim()) seg.assistantTexts.push(t.trim());
        }
        if (part?.type !== "tool") continue;
        const name = String(part.tool ?? "tool");
        seg.tools[name] = (seg.tools[name] ?? 0) + 1;
        const action = describePart(part);
        if (action) seg.workChain.push(action);
        const input = part.state?.input ?? {};
        const file = input.filePath ?? input.file_path ?? input.path;
        if (/write|edit|patch|multiedit/i.test(name) && typeof file === "string") {
          const rel = path.isAbsolute(file) ? path.relative(cwd, file) : file;
          if (rel && !rel.startsWith("..") && rel !== ".dolly" && !rel.startsWith(".dolly/")) {
            if (!seg.files.includes(rel)) seg.files.push(rel);
          }
        }
        if (/bash/i.test(name) && typeof input.command === "string") {
          const cmd = input.command.slice(0, 160);
          if (cmd && !seg.commands.includes(cmd)) seg.commands.push(cmd);
        }
      }
    }
    seg.workChain = compress(seg.workChain);

    try {
      const dir = mirrorDir();
      fs.mkdirSync(dir, { recursive: true });
      fs.appendFileSync(path.join(dir, \`\${sid}.jsonl\`), JSON.stringify({ ...seg, session: sid }) + "\\n");
    } catch {
      // mirror is best-effort
    }

    try {
      execFileSync("dolly", ["hook", "stop", "--from-stdin"], {
        cwd,
        input: JSON.stringify({
          agent: "opencode",
          session: sid,
          // the user message id: stable across restarts, unlike a position
          turn: seg.uuid,
          turnStartMs,
          text: seg.assistantTexts.join("\\n"),
          tools: Object.keys(seg.tools),
          files: seg.files,
        }),
        encoding: "utf8",
        timeout: 15000,
      });
    } catch {
      // never break the session on a logging failure
    }
  };

  function compress(chain, max = 60) {
    const out = [];
    let last = "";
    let run = 0;
    for (const item of chain) {
      if (item === last) { run++; continue; }
      if (last) out.push(run > 1 ? \`\${last} ×\${run}\` : last);
      last = item;
      run = 1;
    }
    if (last) out.push(run > 1 ? \`\${last} ×\${run}\` : last);
    return out.length <= max ? out : [...out.slice(0, max), \`… +\${out.length - max} more actions\`];
  }

  function mirrorDir() {
    const base =
      process.env.DOLLY_OPENCODE_DIR ||
      path.join(os.homedir(), ".local/share/opencode/dolly");
    return path.join(base, cwd.replace(/[^a-zA-Z0-9]/g, "-"));
  }

  /**
   * Display-only commands carry frontmatter "direct: true" and are meant to
   * show their output verbatim (/dolly-board), not have a model narrate it.
   * Interception happens in command.execute.before: the first !\`cmd\` line of
   * the template runs as a session shell message — its output lands in the
   * transcript without an LLM round-trip — then we throw, which skips the
   * model call. If the shell route fails we stand down and let the normal
   * prompt flow handle it instead of showing the user nothing.
   */
  const DIRECT = new Map();

  function scanDirectCommands() {
    const cfgHome = process.env.XDG_CONFIG_HOME || path.join(os.homedir(), ".config");
    const dirs = [
      path.join(cwd, ".opencode", "commands"),
      path.join(cfgHome, "opencode", "commands"),
    ];
    for (const dir of dirs) {
      let files = [];
      try {
        files = fs.readdirSync(dir);
      } catch {
        continue;
      }
      for (const f of files) {
        if (!f.startsWith("dolly-") || !f.endsWith(".md")) continue;
        const name = f.slice(0, -3);
        if (DIRECT.has(name)) continue;
        let md = "";
        try {
          md = fs.readFileSync(path.join(dir, f), "utf8");
        } catch {
          continue;
        }
        if (!/^direct:[ ]*true[ ]*$/m.test(md)) continue;
        const start = md.indexOf("!\`");
        if (start === -1) continue;
        const end = md.indexOf("\`", start + 2);
        if (end === -1) continue;
        DIRECT.set(name, md.slice(start + 2, end).trim());
      }
    }
  }

  /** $ARGUMENTS / $\{ARGUMENTS:-default\} / $1..$9, resolved before the shell sees them */
  function substituteArgs(tpl, args) {
    const list = args.trim() ? args.split(/\\s+/) : [];
    let out = tpl;
    const DEF = "$" + "{ARGUMENTS:-";
    let idx;
    while ((idx = out.indexOf(DEF)) !== -1) {
      const end = out.indexOf("}", idx);
      const fallback = end === -1 ? "" : out.slice(idx + DEF.length, end);
      out = out.slice(0, idx) + (list[0] ?? fallback) + out.slice(end + 1);
    }
    out = out.split("$ARGUMENTS").join(args);
    for (let i = 9; i >= 1; i--) out = out.split("$" + i).join(list[i - 1] ?? "");
    return out;
  }

  async function runDirectCommand(input) {
    scanDirectCommands();
    const tpl = DIRECT.get(input.command);
    if (!tpl) return false;
    const cmd = substituteArgs(tpl, String(input.arguments ?? ""));
    try {
      await client.session.shell({
        path: { id: input.sessionID },
        body: { command: cmd, agent: "build" },
      });
      return true;
    } catch {
      return false; // shell route unavailable — normal prompt flow takes over
    }
  }

  return {
    // a new user turn began: reset timing and let the next LLM call re-read context
    "chat.message": async () => {
      turnStartMs = Date.now();
      cache.at = 0;
    },
    "experimental.chat.system.transform": async (_input, output) => {
      const ctx = dollyContext();
      if (ctx && ctx.trim()) output.system.push(ctx);
    },
    "experimental.session.compacting": async (_input, output) => {
      cache.at = 0; // compaction means long time passed; force fresh context
      const ctx = dollyContext();
      if (ctx && ctx.trim()) output.context.push(ctx);
    },
    "command.execute.before": async (input) => {
      let handled = false;
      try {
        handled = await runDirectCommand(input);
      } catch {
        handled = false;
      }
      // a throw here cancels the LLM prompt — the command already showed its output
      if (handled) throw new Error("dolly: display-only command");
    },
    event: async ({ event }) => {
      try {
        if (event?.type !== "session.idle") return;
        const sid = event.properties?.sessionID ?? event.properties?.info?.id;
        if (!sid) return;
        await finishTurn(String(sid));
      } catch {
        // never surface anything into the session
      }
    },
  };
};
`;

/**
 * Mirror a directory dolly owns outright (skills/dolly, commands/dolly): write
 * what changed, and delete what the package no longer ships. Copy-only left a
 * removed command installed forever, still pointing at a subcommand that no
 * longer exists.
 */
function syncTree(from: string, to: string, dry: boolean): string {
  if (!isDir(from)) return `skip (missing in package): ${from}`;
  const want = new Map<string, string>();
  const walk = (dir: string, rel = '') => {
    for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
      const r = path.join(rel, e.name);
      if (e.isDirectory()) walk(path.join(dir, e.name), r);
      else if (e.isFile()) want.set(r, readTextOr(path.join(dir, e.name)));
    }
  };
  walk(from);
  let wrote = 0;
  for (const [rel, content] of want) {
    const dest = path.join(to, rel);
    if (readTextOr(dest, '\u0000') === content) continue;
    wrote++;
    if (!dry) writeText(dest, content);
  }
  const removed = pruneDir(to, (rel) => !want.has(rel), dry);
  if (!wrote && !removed.length) return `up-to-date ${to}`;
  const parts = [wrote && `${wrote} file(s) written`, removed.length && `removed ${removed.join(', ')}`];
  return `synced ${path.relative(PKG_ROOT, from)} → ${to} (${parts.filter(Boolean).join('; ')})`;
}

/** delete files under `dir` that `stale(relPath)` flags; returns their relative paths */
function pruneDir(dir: string, stale: (rel: string) => boolean, dry: boolean): string[] {
  const out: string[] = [];
  if (!isDir(dir)) return out;
  const walk = (d: string, rel = '') => {
    for (const e of fs.readdirSync(d, { withFileTypes: true })) {
      const r = path.join(rel, e.name);
      if (e.isDirectory()) walk(path.join(d, e.name), r);
      else if (stale(r)) {
        out.push(r);
        if (!dry) fs.rmSync(path.join(d, e.name), { force: true });
      }
    }
  };
  walk(dir);
  return out;
}

/**
 * Read, change and write back a JSON config the user owns. A file that does not
 * parse — opencode and gemini allow comments, a hand edit left a trailing comma,
 * a crash truncated ~/.claude.json — is skipped with instructions, never
 * replaced by a fresh object holding only dolly's key.
 */
function editJson(
  file: string,
  what: string,
  mutate: (cfg: Record<string, any>) => boolean,
  dry: boolean,
  fallback: Record<string, any> = {},
): string {
  let cfg: Record<string, any>;
  try {
    cfg = readJsonForUpdate<Record<string, any>>(file, fallback);
  } catch (err) {
    if (!(err instanceof JsonFileError)) throw err;
    return `skipped ${file} — ${err.message}. Add ${what} by hand.`;
  }
  if (!mutate(cfg)) return `up-to-date ${file} (${what})`;
  if (!dry) writeJson(file, cfg);
  return `wrote ${file} (${what})`;
}

const same = (a: unknown, b: unknown) => JSON.stringify(a ?? null) === JSON.stringify(b ?? null);

/**
 * `mcpServers.dolly`, merged into what is there: a user who pointed `command` at
 * an absolute path, or added `env`, keeps both.
 */
function mergeMcpJson(file: string, key: string, dry: boolean): string {
  return editJson(
    file,
    `${key}.dolly`,
    (cfg) => {
      cfg[key] = cfg[key] ?? {};
      const prev = cfg[key].dolly;
      const next = { ...(prev ?? {}), command: prev?.command ?? MCP_SERVER.command, args: MCP_SERVER.args };
      if (same(prev, next)) return false;
      cfg[key].dolly = next;
      return true;
    },
    dry,
  );
}

/**
 * zcode keeps MCP servers under nested `mcp.servers`, and its `command` is a
 * STRING with the rest in `args` — the OpenCode-style array form crashes the
 * settings UI. Only canonical fields: the schema is strict about extra keys.
 */
function mergeZcodeMcp(file: string, dry: boolean): string {
  return editJson(
    file,
    'mcp.servers.dolly',
    (cfg) => {
      cfg.mcp = cfg.mcp ?? {};
      cfg.mcp.servers = cfg.mcp.servers ?? {};
      const prev = cfg.mcp.servers.dolly;
      const next = { type: 'stdio', command: prev?.command ?? 'dolly', args: ['mcp'], enabled: prev?.enabled ?? true };
      if (same(prev, next)) return false;
      cfg.mcp.servers.dolly = next;
      return true;
    },
    dry,
  );
}

/**
 * Install the dolly slash-commands for zcode (.zcode/commands/dolly-<name>.md),
 * with the zcode conversion applied. Unlike pi/opencode this is a separate
 * loop rather than an installNamedPrompts flag: the converter is two rewrites,
 * not a passthrough/one-rewrite toggle.
 */
function installZcodeCommands(dir: string, dry: boolean): string[] {
  return installCommandFiles(dir, dry, toZcodeCommand);
}

/* ---------------------------- zcode plugin files --------------------------- */
/*
 * zcode ignores workspace-level hooks entirely in this version — hooks only
 * load from user config or a plugin. The plugin route needs no edit to files
 * zcode owns: a local directory acts as a marketplace, so `dolly install
 * zcode` scaffolds one under ~/.zcode/marketplaces/dolly/ and the human adds
 * it in Settings → Plugin Management → Discover (the `+` button) and clicks
 * Get. Session-start emits dolly's Claude-compatible JSON envelope
 * (hookSpecificOutput.additionalContext), which zcode accepts unchanged.
 */

function zcodeMarketplaceJson(version: string): string {
  return `${JSON.stringify(
    {
      name: 'dolly-local',
      plugins: [
        {
          name: 'dolly',
          description: 'dolly task memory — session-start context injection and per-turn auto-log',
          version,
          source: './dolly',
        },
      ],
    },
    null,
    2,
  )}\n`;
}

function zcodePluginJson(version: string): string {
  return `${JSON.stringify(
    {
      name: 'dolly',
      version,
      description: 'dolly task memory — session-start context injection and per-turn auto-log',
      hooks: 'hooks',
    },
    null,
    2,
  )}\n`;
}

const ZCODE_HOOKS_JSON = `${JSON.stringify(
  {
    hooks: {
      SessionStart: [
        {
          hooks: [{ type: 'process', command: 'dolly', args: ['hook', 'session-start'], timeoutMs: 15000 }],
        },
      ],
      Stop: [
        {
          hooks: [
            { type: 'process', command: 'dolly', args: ['hook', 'stop', '--from-stdin'], timeoutMs: 15000 },
          ],
        },
      ],
    },
  },
  null,
  2,
)}\n`;

function installZcodePlugin(marketplaceDir: string, version: string, dry: boolean): string[] {
  const pluginRoot = path.join(marketplaceDir, 'dolly');
  return [
    // the manifest's exact home is not documented; write both candidate paths
    writeFileIdempotent(path.join(marketplaceDir, 'marketplace.json'), zcodeMarketplaceJson(version), dry),
    writeFileIdempotent(
      path.join(marketplaceDir, '.zcode-marketplace', 'marketplace.json'),
      zcodeMarketplaceJson(version),
      dry,
    ),
    writeFileIdempotent(path.join(pluginRoot, '.zcode-plugin', 'plugin.json'), zcodePluginJson(version), dry),
    writeFileIdempotent(path.join(pluginRoot, 'hooks', 'hooks.json'), ZCODE_HOOKS_JSON, dry),
  ];
}

function tomlBlock(file: string, dry: boolean): string {
  const src = readTextOr(file);
  const marker = '# dolly:start';
  const endMarker = '# dolly:end';
  const block = [
    marker,
    '[mcp_servers.dolly]',
    'command = "dolly"',
    'args = ["mcp"]',
    endMarker,
  ].join('\n');
  let next: string;
  const i = src.indexOf(marker);
  const j = i === -1 ? -1 : src.indexOf(endMarker, i);
  if (i !== -1 && j !== -1) next = src.slice(0, i) + block + src.slice(j + endMarker.length);
  else if (/^\s*\[mcp_servers\.dolly\]\s*$/m.test(src)) {
    // registered outside our markers (`codex mcp add dolly`): a second table
    // with the same name is invalid TOML and codex would refuse the whole file
    return `up-to-date ${file} ([mcp_servers.dolly] already defined)`;
  } else next = `${src}${src && !src.endsWith('\n') ? '\n' : ''}${src ? '\n' : ''}${block}\n`;
  if (next !== src && !dry) writeText(file, next);
  return `${next === src ? 'up-to-date' : 'wrote'} ${file}`;
}

/**
 * The hook commands as written into a (committed) settings.json. Guarded, so a
 * teammate who clones the repo without dolly installed gets silence, not a
 * "command not found" error on every session start and every turn.
 */
export function hookCommand(sub: 'session-start' | 'stop'): string {
  return `command -v dolly >/dev/null 2>&1 && dolly hook ${sub} || true`;
}

/**
 * Register the SessionStart / Stop hooks in settings.json. These are what make
 * dolly automatic: context injected on every new session, and a step logged for
 * every finished turn. Matched by command string so re-running never duplicates;
 * an older bare `dolly hook …` entry is upgraded to the guarded form in place.
 */
function mergeHooks(file: string, dry: boolean): string {
  const wanted = { SessionStart: 'session-start', Stop: 'stop' } as const;
  return editJson(
    file,
    'hooks: SessionStart, Stop',
    (cfg) => {
      cfg.hooks = cfg.hooks ?? {};
      let changed = false;
      for (const [event, sub] of Object.entries(wanted)) {
        const command = hookCommand(sub);
        const groups: any[] = Array.isArray(cfg.hooks[event]) ? cfg.hooks[event] : [];
        let found = false;
        for (const g of groups) {
          for (const h of g?.hooks ?? []) {
            if (typeof h?.command !== 'string' || !h.command.includes(`dolly hook ${sub}`)) continue;
            found = true;
            if (h.command === `dolly hook ${sub}`) {
              h.command = command;
              changed = true;
            }
          }
        }
        if (found) continue;
        groups.push({ hooks: [{ type: 'command', command, timeout: 15 }] });
        cfg.hooks[event] = groups;
        changed = true;
      }
      return changed;
    },
    dry,
  );
}

/**
 * Remove the footprint of the pre-rename name.
 *
 * Without this an upgrade leaves a working install *and* a dead one: two skill
 * directories, two command sets, two MCP servers, two hook entries, and a
 * stale instruction block that `setBlock` cannot update because its marker no
 * longer matches. Idempotent — a no-op once there is nothing old left.
 */
function cleanLegacy(project: string, base: string, dry: boolean): string[] {
  const out: string[] = [];
  const OLD = 'dollie';

  for (const rel of [
    path.join(base, 'skills', OLD),
    path.join(base, 'skills', `${OLD}-planning`),
    path.join(base, 'commands', OLD),
  ]) {
    if (!isDir(rel)) continue;
    if (!dry) rmrf(rel);
    out.push(`removed ${rel}`);
  }

  // stale instruction blocks: rename the marker so the block is updated in
  // place instead of a second one being appended below it
  for (const file of [
    path.join(project, 'CLAUDE.md'),
    path.join(home(), '.claude', 'CLAUDE.md'),
    path.join(project, 'AGENTS.md'),
    path.join(project, 'GEMINI.md'),
    path.join(project, '.github', 'copilot-instructions.md'),
  ]) {
    const src = readTextOr(file);
    if (!src.includes(`<!-- ${OLD}:instructions -->`)) continue;
    if (!dry) writeText(file, src.replace(new RegExp(`<!--(\\s*/?\\s*)${OLD}:`, 'g'), '<!--$1dolly:'));
    out.push(`renamed stale instruction block in ${file}`);
  }

  for (const [file, key] of [
    [path.join(project, '.mcp.json'), 'mcpServers'],
    [path.join(project, '.cursor', 'mcp.json'), 'mcpServers'],
    [path.join(project, '.gemini', 'settings.json'), 'mcpServers'],
    [path.join(home(), '.claude.json'), 'mcpServers'],
  ] as const) {
    if (!exists(file)) continue;
    const res = editJson(
      file,
      `${key}.${OLD} removal`,
      (cfg) => {
        if (!cfg[key]?.[OLD]) return false;
        delete cfg[key][OLD];
        return true;
      },
      dry,
    );
    if (!res.startsWith('up-to-date')) out.push(res);
  }

  // only the old binary's own hook commands — never a group that merely
  // mentions the word, like a lint hook run from a checkout named `dollie/`
  const OLD_HOOK = /^\s*(?:npx\s+)?dollie\s+hook\b/;
  const settings = path.join(base, 'settings.json');
  if (exists(settings)) {
    const res = editJson(
      settings,
      `${OLD} hook removal`,
      (cfg) => {
        let touched = false;
        for (const event of Object.keys(cfg.hooks ?? {})) {
          const groups: any[] = Array.isArray(cfg.hooks[event]) ? cfg.hooks[event] : [];
          const kept = [];
          for (const g of groups) {
            const hooks: any[] = Array.isArray(g?.hooks) ? g.hooks : [];
            const left = hooks.filter((h) => !(typeof h?.command === 'string' && OLD_HOOK.test(h.command)));
            if (left.length !== hooks.length) touched = true;
            if (left.length || !hooks.length) kept.push(left.length === hooks.length ? g : { ...g, hooks: left });
          }
          cfg.hooks[event] = kept;
        }
        return touched;
      },
      dry,
    );
    if (!res.startsWith('up-to-date')) out.push(res);
  }
  return out;
}


/**
 * Is the dolly Claude Code plugin installed and enabled for this user? It ships
 * its own skills, commands, MCP server and hooks, so a user-level install on
 * top of it only doubles every one of them.
 */
export function claudePluginEnabled(project: string): boolean {
  let installed: Record<string, unknown> = {};
  try {
    const reg = JSON.parse(readTextOr(path.join(home(), '.claude', 'plugins', 'installed_plugins.json')) || '{}');
    installed = reg?.plugins ?? {};
  } catch {
    return false;
  }
  const keys = Object.keys(installed).filter((k) => /^dolly@/.test(k));
  if (!keys.length) return false;
  const enabled = (file: string) => {
    try {
      return JSON.parse(readTextOr(file) || '{}')?.enabledPlugins ?? {};
    } catch {
      return {};
    }
  };
  const flags = { ...enabled(path.join(home(), '.claude', 'settings.json')), ...enabled(path.join(project, '.claude', 'settings.json')) };
  return keys.some((k) => flags[k] !== false);
}

/** the two dolly skills, mirrored into an agent's skills directory */
function syncSkills(skillsDir: string, dry: boolean): string[] {
  return ['dolly', 'dolly-planning'].map((name) =>
    syncTree(path.join(PKG_ROOT, 'skills', name), path.join(skillsDir, name), dry),
  );
}

/** a target, or part of one, that has no user-level form */
const projectOnly = (what: string) => `skipped ${what} — project-only; rerun without --global to write it`;

export const TARGETS: Target[] = [
  {
    id: 'claude',
    label: 'Claude Code',
    detect: (p) => isDir(path.join(home(), '.claude')) || isDir(path.join(p, '.claude')),
    install(project, opts) {
      const base = opts.global ? path.join(home(), '.claude') : path.join(project, '.claude');
      const out: string[] = cleanLegacy(project, base, opts.dryRun);
      const plugin = claudePluginEnabled(project);
      if (plugin && opts.global) {
        // both are yours alone: the plugin already provides all of it
        out.push('skipped skills, commands, MCP and hooks — the dolly plugin is enabled and provides them');
        out.push(writeBlock(path.join(home(), '.claude', 'CLAUDE.md'), AGENT_BLOCK, opts.dryRun));
        return out;
      }
      if (plugin) {
        // project files are for teammates without the plugin; the plugin's
        // hooks step aside for these at runtime
        out.push('note: the dolly plugin is enabled for you — its hooks defer to these; its MCP server and commands will show beside the project ones');
      }
      out.push(...syncSkills(path.join(base, 'skills'), opts.dryRun));
      out.push(syncTree(path.join(PKG_ROOT, 'commands'), path.join(base, 'commands', 'dolly'), opts.dryRun));
      out.push(
        writeBlock(
          opts.global ? path.join(home(), '.claude', 'CLAUDE.md') : path.join(project, 'CLAUDE.md'),
          AGENT_BLOCK,
          opts.dryRun,
        ),
      );
      if (opts.mcp) {
        out.push(
          mergeMcpJson(
            opts.global ? path.join(home(), '.claude.json') : path.join(project, '.mcp.json'),
            'mcpServers',
            opts.dryRun,
          ),
        );
      }
      if (opts.hooks !== false) {
        out.push(mergeHooks(path.join(base, 'settings.json'), opts.dryRun));
      }
      return out;
    },
  },
  {
    id: 'codex',
    label: 'Codex CLI',
    detect: () => isDir(path.join(home(), '.codex')),
    install(project, opts) {
      const out = [
        writeBlock(
          opts.global ? path.join(home(), '.codex', 'AGENTS.md') : path.join(project, 'AGENTS.md'),
          AGENT_BLOCK,
          opts.dryRun,
        ),
      ];
      // codex reads MCP servers from the user config only; a project install
      // must not quietly edit it
      if (opts.mcp) {
        out.push(
          opts.global
            ? tomlBlock(path.join(home(), '.codex', 'config.toml'), opts.dryRun)
            : 'skipped MCP — codex reads it from ~/.codex/config.toml only; `dolly install codex --global` registers it',
        );
      }
      return out;
    },
  },
  {
    id: 'cursor',
    label: 'Cursor',
    detect: (p) => isDir(path.join(home(), '.cursor')) || isDir(path.join(p, '.cursor')),
    install(project, opts) {
      const out: string[] = [];
      if (opts.global) {
        out.push('skipped rules — Cursor keeps user rules in its settings UI, not a file; paste the dolly block there');
      } else {
        const rule = [
          '---',
          'description: dolly task memory and planning',
          'alwaysApply: true',
          '---',
          '',
          AGENT_BLOCK,
          '',
        ].join('\n');
        out.push(writeFileIdempotent(path.join(project, '.cursor', 'rules', 'dolly.mdc'), rule, opts.dryRun));
      }
      if (opts.mcp) {
        out.push(
          mergeMcpJson(
            opts.global ? path.join(home(), '.cursor', 'mcp.json') : path.join(project, '.cursor', 'mcp.json'),
            'mcpServers',
            opts.dryRun,
          ),
        );
      }
      return out;
    },
  },
  {
    id: 'windsurf',
    label: 'Windsurf',
    detect: (p) => isDir(path.join(home(), '.codeium')) || isDir(path.join(p, '.windsurf')),
    install(project, opts) {
      return [
        opts.global
          ? writeBlock(path.join(home(), '.codeium', 'windsurf', 'memories', 'global_rules.md'), AGENT_BLOCK, opts.dryRun)
          : writeFileIdempotent(path.join(project, '.windsurf', 'rules', 'dolly.md'), `${AGENT_BLOCK}\n`, opts.dryRun),
      ];
    },
  },
  {
    id: 'copilot',
    label: 'GitHub Copilot',
    // any `.github/` (every repo with CI has one) is not a sign of Copilot
    detect: (p) =>
      exists(path.join(p, '.github', 'copilot-instructions.md')) ||
      isDir(path.join(home(), '.config', 'github-copilot')),
    install(project, opts) {
      if (opts.global) return [projectOnly('.github/copilot-instructions.md')];
      return [
        writeBlock(path.join(project, '.github', 'copilot-instructions.md'), AGENT_BLOCK, opts.dryRun),
      ];
    },
  },
  {
    id: 'gemini',
    label: 'Gemini CLI',
    detect: () => isDir(path.join(home(), '.gemini')),
    install(project, opts) {
      const dir = opts.global ? path.join(home(), '.gemini') : project;
      const out = [writeBlock(path.join(dir, 'GEMINI.md'), AGENT_BLOCK, opts.dryRun)];
      if (opts.mcp) {
        out.push(
          mergeMcpJson(
            opts.global ? path.join(home(), '.gemini', 'settings.json') : path.join(project, '.gemini', 'settings.json'),
            'mcpServers',
            opts.dryRun,
          ),
        );
      }
      return out;
    },
  },
  {
    id: 'opencode',
    label: 'opencode',
    detect: (p) =>
      isDir(path.join(home(), '.config', 'opencode')) ||
      isDir(path.join(home(), '.opencode')) ||
      isDir(path.join(p, '.opencode')),
    install(project, opts) {
      // opencode discovers skills/commands/plugins under ~/.config/opencode
      // globally and .opencode/ per-project. Skills also load from
      // .claude/skills/, but writing .opencode/skills keeps the footprint
      // explicit rather than relying on a compatibility mode.
      const base = opts.global ? path.join(home(), '.config', 'opencode') : path.join(project, '.opencode');
      const out: string[] = [];
      out.push(...syncSkills(path.join(base, 'skills'), opts.dryRun));
      // slash commands pass through unmodified: opencode runs !`cmd` natively
      out.push(...installNamedPrompts(path.join(base, 'commands'), opts.dryRun, true));
      if (opts.hooks !== false) {
        out.push(writeFileIdempotent(path.join(base, 'plugins', 'dolly.js'), OPENCODE_PLUGIN, opts.dryRun));
      }
      out.push(
        writeBlock(
          opts.global
            ? path.join(home(), '.config', 'opencode', 'AGENTS.md')
            : path.join(project, 'AGENTS.md'),
          AGENT_BLOCK,
          opts.dryRun,
        ),
      );
      if (opts.mcp) {
        const file = opts.global
          ? path.join(home(), '.config', 'opencode', 'opencode.json')
          : path.join(project, 'opencode.json');
        out.push(
          editJson(
            file,
            'mcp.dolly',
            (cfg) => {
              cfg.mcp = cfg.mcp ?? {};
              const prev = cfg.mcp.dolly;
              const next = {
                ...(prev ?? {}),
                type: 'local',
                command: prev?.command ?? ['dolly', 'mcp'],
                enabled: prev?.enabled ?? true,
              };
              if (same(prev, next)) return false;
              cfg.mcp.dolly = next;
              return true;
            },
            opts.dryRun,
            { $schema: 'https://opencode.ai/config.json' },
          ),
        );
      }
      return out;
    },
  },
  {
    id: 'zcode',
    label: 'ZCode',
    detect: (p) => isDir(path.join(home(), '.zcode')) || isDir(path.join(p, '.zcode')),
    install(project, opts) {
      const out: string[] = [];
      // skills, commands and MCP are repo-shared: teammates get them on
      // checkout with no install of their own
      if (opts.global) {
        out.push(projectOnly('.zcode/ skills, commands and MCP (zcode reads them per workspace)'));
      } else {
        const base = path.join(project, '.zcode');
        out.push(...syncSkills(path.join(base, 'skills'), opts.dryRun));
        out.push(...installZcodeCommands(path.join(base, 'commands'), opts.dryRun));
        out.push(writeBlock(path.join(project, 'AGENTS.md'), AGENT_BLOCK, opts.dryRun));
        if (opts.mcp) out.push(mergeZcodeMcp(path.join(base, 'config.json'), opts.dryRun));
      }
      // hooks cannot ride along in workspace config — zcode ignores them there
      // (config_project_hooks_ignored) — so they ship as a plugin the user
      // enables once: local marketplace, Get on the Discover tab. User-level by
      // nature, whichever scope was asked for.
      if (opts.hooks !== false) {
        const marketplaceDir = path.join(home(), '.zcode', 'marketplaces', 'dolly');
        out.push(...installZcodePlugin(marketplaceDir, VERSION, opts.dryRun));
        out.push(
          `plugin scaffolded at ${marketplaceDir} — one manual step: zcode Settings → ` +
            'Plugin Management → Discover → "+" → add that folder as a local marketplace → Get "dolly"',
        );
      }
      return out;
    },
  },
  {
    id: 'pi',
    label: 'pi',
    detect: (p) => isDir(path.join(home(), '.pi', 'agent')) || isDir(path.join(p, '.pi')),
    install(project, opts) {
      // pi's skill discovery differs by scope: global lives under
      // ~/.pi/agent/skills, but a trusted project is scanned at .pi/skills
      // (NOT .pi/agent/skills). Instructions + MCP use the usual repo files.
      const skills = opts.global
        ? path.join(home(), '.pi', 'agent', 'skills')
        : path.join(project, '.pi', 'skills');
      const out: string[] = [];
      out.push(...syncSkills(skills, opts.dryRun));
      // ~/.pi/agent/AGENTS.md is pi's global context file. NOT SYSTEM.md: that
      // one replaces pi's entire default system prompt — tools, guidelines and
      // all — with nothing but this block.
      out.push(
        writeBlock(
          opts.global ? path.join(home(), '.pi', 'agent', 'AGENTS.md') : path.join(project, 'AGENTS.md'),
          AGENT_BLOCK,
          opts.dryRun,
        ),
      );
      if (opts.mcp) {
        out.push(
          mergeMcpJson(
            opts.global ? path.join(home(), '.pi', 'agent', 'mcp.json') : path.join(project, '.mcp.json'),
            'mcpServers',
            opts.dryRun,
          ),
        );
      }
      // Slash commands install as prompt templates. pi discovers these
      // globally at ~/.pi/agent/prompts and per-project at <repo>/.pi/prompts.
      const prompts = opts.global
        ? path.join(home(), '.pi', 'agent', 'prompts')
        : path.join(project, '.pi', 'prompts');
      out.push(...installNamedPrompts(prompts, opts.dryRun, false));
      // Auto-inject extension is global-only: pi loads extensions from
      // ~/.pi/agent/extensions. Repo-local extension loading is unconfirmed.
      if (opts.global && opts.hooks !== false) {
        out.push(
          writeFileIdempotent(
            path.join(home(), '.pi', 'agent', 'extensions', 'dolly.ts'),
            PI_EXTENSION,
            opts.dryRun,
          ),
        );
      }
      return out;
    },
  },
  {
    id: 'agents',
    label: 'AGENTS.md (generic)',
    detect: (p) => exists(path.join(p, 'AGENTS.md')),
    install(project, opts) {
      if (opts.global) return [projectOnly('AGENTS.md')];
      return [writeBlock(path.join(project, 'AGENTS.md'), AGENT_BLOCK, opts.dryRun)];
    },
  },
];

export function detectTargets(project: string): Target[] {
  return TARGETS.filter((t) => t.detect(project));
}

export function installTargets(
  project: string,
  ids: string[],
  opts: InstallOpts,
): { target: Target; log: string[] }[] {
  const chosen = ids.length
    ? TARGETS.filter((t) => ids.includes(t.id))
    : detectTargets(project);
  const unknown = ids.filter((id) => !TARGETS.some((t) => t.id === id));
  if (unknown.length) {
    throw new Error(
      `unknown agent(s): ${unknown.join(', ')} — known: ${TARGETS.map((t) => t.id).join(', ')}`,
    );
  }
  return chosen.map((t) => ({ target: t, log: t.install(project, opts) }));
}

export { AGENT_BLOCK };
